# Generated by Django 3.2.16 on 2022-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yengine', '0002_auto_20221214_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBSScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_scene_name', models.CharField(max_length=255, verbose_name='Scene name in OBS')),
                ('obs_scene_description', models.TextField(verbose_name='Scene description')),
                ('obs_scene_structure', models.TextField(verbose_name='Scene structure content')),
            ],
        ),
    ]
