# Generated by Django 3.2.16 on 2022-12-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yengine', '0003_obsscene'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_name', models.CharField(blank=True, max_length=255, verbose_name='Audio file name')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media')),
                ('timing', models.IntegerField(default=0, verbose_name='Time in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='AudioGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255, verbose_name='Playlist name')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('timing', models.IntegerField(default=0, verbose_name='Time in seconds')),
                ('audio_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Code name')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yengine.audiofile')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yengine.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_items',
            field=models.ManyToManyField(through='yengine.PlaylistItem', to='yengine.AudioFile'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yengine.audiogenre'),
        ),
    ]
