# Generated by Django 3.2.16 on 2022-12-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yengine', '0006_channellivestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='enable_light_chat',
            field=models.BooleanField(default=False, verbose_name='Use light chat for scan'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yengine.playlist', verbose_name='Stream playlist'),
        ),
        migrations.AlterField(
            model_name='streamphase',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yengine.playlist', verbose_name='Stream phase playlist'),
        ),
    ]
